src/Majordesk/AppBundle/Entity/Exercice.php
<?php

namespace Majordesk\AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Exercice
 *
 * @ORM\Table(name="exercice")
 * @ORM\Entity(repositoryClass="Majordesk\AppBundle\Entity\ExerciceRepository")
 */
class Exercice
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var boolean
     *
     * @ORM\Column(name="favoris", type="boolean")
     */
    private $favoris;
	
	/**
     * @var boolean
     *
     * @ORM\Column(name="autonomie", type="boolean")
     */
    private $autonomie;

    /**
     * @var smallint
     *
     * @ORM\Column(name="selection", type="smallint")
     */
    private $selection;
	
	/**
     * @var \DateTime
     *
     * @ORM\Column(name="temps", type="time")
     */
    private $temps;
	
	/**
     * @var string
     *
     * @ORM\Column(name="statut", type="string", length=1)
     */
    private $statut;
	
	/**
     * @var string
     *
     * @ORM\Column(name="queue", type="string", length=1)
     */
    private $queue;
	
	/**
     * @var \DateTime
     *
     * @ORM\Column(name="date_queue", type="datetime")
     */
    private $date_queue;

    /**
	* @ORM\ManyToOne(targetEntity="Majordesk\AppBundle\Entity\ModExercice", inversedBy="exercices")
	* @ORM\JoinColumn(nullable=false)
	*/
	private $mod_exercice;

	/**
	* @ORM\ManyToOne(targetEntity="Majordesk\AppBundle\Entity\Eleve", inversedBy="exercices")
	* @ORM\JoinColumn(nullable=false)
	*/
	private $eleve;
	
	/**
	* @ORM\OneToMany(targetEntity="Majordesk\AppBundle\Entity\Question", mappedBy="exercice", cascade={"persist", "remove"})
	*/
	private $questions;
	

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set favoris
     *
     * @param boolean $favoris
     * @return Exercice
     */
    public function setFavoris($favoris)
    {
        $this->favoris = $favoris;
    
        return $this;
    }

    /**
     * Get favoris
     *
     * @return boolean 
     */
    public function getFavoris()
    {
        return $this->favoris;
    }
	
	/**
     * Set autonomie
     *
     * @param boolean $autonomie
     * @return Exercice
     */
    public function setAutonomie($autonomie)
    {
        $this->autonomie = $autonomie;
    
        return $this;
    }

    /**
     * Get autonomie
     *
     * @return boolean 
     */
    public function getAutonomie()
    {
        return $this->autonomie;
    }

    /**
     * Set selection
     *
     * @param boolean $selection
     * @return Exercice
     */
    public function setSelection($selection)
    {
        $this->selection = $selection;
    
        return $this;
    }

    /**
     * Get selection
     *
     * @return boolean 
     */
    public function getSelection()
    {
        return $this->selection;
    }
	
	/**
     * Set queue
     *
     * @param boolean $queue
     * @return Exercice
     */
    public function setQueue($queue)
    {
        $this->queue = $queue;
    
        return $this;
    }

    /**
     * Get queue
     *
     * @return boolean 
     */
    public function getQueue()
    {
        return $this->queue;
    }
	
	/**
     * Set date_queue
     *
     * @param boolean $date_queue
     * @return Exercice
     */
    public function setDateQueue($date_queue)
    {
        $this->date_queue = $date_queue;
    
        return $this;
    }

    /**
     * Get date_queue
     *
     * @return boolean 
     */
    public function getDateQueue()
    {
        return $this->date_queue;
    }
	
	/**
     * Get derniere date
     *
     * @return boolean 
     */
    public function getDerniereDate()
    {
        foreach( $this->getQuestions() as $question ) {
			if (!isset($derniere_date)) {
				$derniere_date = $question->getDateEnregistrement();
			}
			else {
				$derniere_date = max( $derniere_date, $question->getDateEnregistrement() );
			}
		}
		
		return $derniere_date;
    }
	
	/**
     * Get selection
     *
     * @return boolean 
     */
    // public function getTemps()
    // {
		// $temps = new \DateTime("00:00:00");
		// $heures = 0;
		// $minutes = 0;
		// $secondes = 0;
        // foreach( $this->getQuestions() as $question ) {
			// $temps_question = $question->getTemps();		
			// $heures += intval($temps_question->format('G'));
			// $minutes += intval($temps_question->format('i'));
			// $secondes += intval($temps_question->format('s'));
		// }
		
		// $temps->setTime($heures, $minutes, $secondes);
		
		// return $temps;
    // }
	
	/**
     * Set temps
     *
     * @param \DateTime $temps
     * @return Question
     */
    public function setTemps($temps)
    {
        $this->temps = $temps;
    
        return $this;
    }

    /**
     * Get temps
     *
     * @return \DateTime 
     */
    public function getTemps()
    {
        return $this->temps;
    }
	
	/**
     * Get selection
     *
     * @return boolean 
     */
    public function getNiveau()
    {
		return $this->mod_exercice->getNiveau();
    }
	
	/**
     * Get selection
     *
     * @return boolean 
     */
    public function getNombreEssais()
    {
		$essais = 0;
        foreach( $this->getQuestions() as $question ) {
			$essais += $question->getNombreEssais();
		}
		
		return $essais;
    }
	
	/**
     * Get NombreQuestions
     *
     * @return boolean 
     */
    public function getNombreQuestions()
    {
		return count($this->questions);
    }
	
	/**
     * Get NombreQuestionsCommencees
     *
     * @return boolean 
     */
    public function getNombreQuestionsCommencees($statut_non_commence)
    {
		$nb_questions_commencees = 0;
		foreach( $this->questions as $question ) {
			if ( $question->getStatut() != $statut_non_commence ) {
				$nb_questions_commencees += 1;
			}
		}
		
		return $nb_questions_commencees;
    }
	
	/**
     * Set statut
     *
     * @param string $statut
     * @return Question
     */
    public function setStatut($statut)
    {
        $this->statut = $statut;
    
        return $this;
    }

    /**
     * Get statut
     *
     * @return string 
     */
    public function getStatut()
    {
        return $this->statut;
    }
	
	/**
     * Update statut
     *
     * @return boolean 
     */
    public function updateStatut()
    {
		// Vars
		$statut_non_commence = 0;
		$statut_non_resolu = 1;
		$statut_resolu = 2;
		
		$non_commence = 0;
		$non_resolu = 0;
		$resolu = 0;
		$questions = $this->getTrueQuestions();
		$nombre_questions = count($questions);
		if ($nombre_questions == 0) {  // à supprimer qd proprification
			$questions = $this->getQuestions();
			$nombre_questions = count($questions);
		}
		
        foreach( $questions as $question ) {
			if ( $question->getStatut() == $statut_resolu ) {
				$resolu++;
			}
			else if ( $question->getStatut() == $statut_non_resolu ) {
				$non_resolu++;
			}
			else {
				$non_commence++;
			}
		}
		
		if ( $resolu == $nombre_questions) {
			$this->statut = $statut_resolu;
		}
		else if ( $non_commence == $nombre_questions) {
			$this->statut = $statut_non_commence;
		}
		else {
			$this->statut = $statut_non_resolu;
		}
    }
    
    /**
     * Set mod_exercice
     *
     * @param \Majordesk\AppBundle\Entity\ModExercice $modExercice
     * @return Exercice
     */
    public function setModExercice(\Majordesk\AppBundle\Entity\ModExercice $modExercice)
    {
        $this->mod_exercice = $modExercice;
    
        return $this;
    }

    /**
     * Get mod_exercice
     *
     * @return \Majordesk\AppBundle\Entity\ModExercice 
     */
    public function getModExercice()
    {
        return $this->mod_exercice;
    }

    /**
     * Set eleve
     *
     * @param \Majordesk\AppBundle\Entity\Eleve $eleve
     * @return Exercice
     */
    public function setEleve(\Majordesk\AppBundle\Entity\Eleve $eleve)
    {
        $this->eleve = $eleve;
    
        return $this;
    }

    /**
     * Get eleve
     *
     * @return \Majordesk\AppBundle\Entity\Eleve 
     */
    public function getEleve()
    {
        return $this->eleve;
    }

    /**
     * Add questions
     *
     * @param \Majordesk\AppBundle\Entity\Question $questions
     * @return Exercice
     */
    public function addQuestion(\Majordesk\AppBundle\Entity\Question $question)
    {
        $this->questions[] = $question;
    
        return $this;
    }

    /**
     * Remove questions
     *
     * @param \Majordesk\AppBundle\Entity\Question $questions
     */
    public function removeQuestion(\Majordesk\AppBundle\Entity\Question $question)
    {
        $this->questions->removeElement($question);
    }
	
	/**
     * Get questions
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function selectQuestionByNumero($numero)
    {
		foreach($this->questions as $question) {
			if ($question->getNumero() == $numero) {
				return $question;
			}
		}
		return null;
    }

    /**
     * Get questions
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getQuestions()
    {
        return $this->questions;
    }
	
	/**
     * Get questions
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getTrueQuestions()
    {
		$questions = array();
        foreach($this->questions as $question) {
			if($question->getModQuestion()->getType() == 'question') {
				$questions[] = $question;
			}
		}
		return $questions;
    }
	
	/**
     * Constructor
     */
    public function __construct()
    {
		$this->favoris = '0';
		$this->autonomie = true;
		$this->selection = 0;
		$this->queue = '0';
		$this->date_queue = new \Datetime("now", new \DateTimeZone('Europe/Paris'));
		$this->temps = new \Datetime("00:00:00");
		$this->statut = '0';
        $this->questions = new \Doctrine\Common\Collections\ArrayCollection();
    }
}

src/Majordesk/AppBundle/Form/Type/ProfesseurType.php
<?php

namespace Majordesk\AppBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Majordesk\AppBundle\Entity\EleveRepository;

class ProfesseurType extends AbstractType
{
	

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('mail'                , 'email', array(
				'attr' => array('class'=>'form-control')
				))
            // ->add('password'            , 'repeated', array(
				// 'type' => 'password',
				// 'invalid_message' => 'Les mots de passe doivent correspondre',
				// 'first_name' => 'pass',
				// 'second_name' => 'confirm',
				// 'first_options'  => array('label' => ' '),
				// 'second_options' => array('label' => 'Confirmation'),
				// ))
            // ->add('salt')
            // ->add('roles')
            ->add('username'              , 'text', array(
				'attr' => array('class'=>'form-control')
				))
            ->add('nom'                 , 'text', array(
				'attr' => array('class'=>'form-control')
				))
            // ->add('actif')
            ->add('heures_donnees'      , 'integer', array(
				'attr' => array('class'=>'form-control')
				))
            ->add('prepa'               , 'choice', array(
				'choices'   => array('MP' => 'MP', 'PSI' => 'PSI', 'PC' => 'PC', 'PT' => 'PT', 'Autre' => 'Autre'),
				'attr' => array('class'=>'form-control')
				))
            ->add('lycee'               , 'text', array(
				'required' => false,
				'attr' => array('class'=>'form-control')
				))
            ->add('adresse'             , 'text', array(
				'required' => false,
				'attr' => array('class'=>'form-control')
				))
            ->add('code_postal'         , 'text', array(
				'required' => false,
				'attr' => array('class'=>'form-control')
				))
            ->add('ville'               , 'text', array(
				'required' => false,
				'attr' => array('class'=>'form-control')
				))
            ->add('telephone'           , 'text', array(
				'required' => false,
				'attr' => array('class'=>'form-control')
				))
            ->add('fin_dispo'           , 'date', array(
				'widget' => 'single_text',
				'format' => 'dd/MM/yyyy',
				'attr' => array('class' =>'form-control datepicker'),
				'invalid_message' => 'La date entrée est incorrecte'
				))
            ->add('notifications', 'integer', array(
				'attr' => array('class'=>'form-control')
				))
            ->add('securite_sociale'    , 'text', array(
				'required' => false,
				'attr' => array('class'=>'form-control')
				))
            ->add('rib'                 , 'text', array(
				'required' => false,
				'attr' => array('class'=>'form-control')
				))
			->add('transport'           , 'choice', array(
				'choices'   => array('Transports en commun' => 'Transports en commun', 'Voiture' => 'Voiture', '2 roues' => '2 roues', 'Vélo' => 'Vélo', 'Autre' => 'Autre'),
				'attr' => array('class'=>'form-control')
				))
			->add('nb_heures_max', 'integer', array(
				'required' => false,
				'attr' => array('class'=>'form-control')
				))
			->add('matieres'         , 'collection', array(
					'type'         => 'entity',
					'options'      => array(
							'class' => 'MajordeskAppBundle:Matiere',
							'property' => 'nom',
							'empty_value' => 'Choisir une matière',
							'attr' => array('class'=>'form-control')
						),
					'required' => false,
					'allow_add'    => true,
                    'allow_delete' => true,
					'by_reference' => false
					))
			->add('disponibilites', 'collection', array(
					'type'         => new DisponibiliteType(),
					'options'      => array(
							'attr' => array('class'=>'form-control')
						),
					'required' => false,
					'allow_add'    => true,
                    'allow_delete' => true
					))
            ->add('date_inscription'    , 'date', array(
				'widget' => 'single_text',
				'format' => 'dd/MM/yyyy',
				'attr' => array('class' =>'form-control datepicker'),
				'invalid_message' => 'La date entrée est incorrecte'
				))
			// ->add('eleves'               , 'collection', array(
					// 'type' => 'entity',
					// 'options' => array(
						// 'class' => 'MajordeskAppBundle:Eleve',
						// 'property' => 'nomEntier',
						// 'group_by' => 'initiale',
						// 'query_builder' => function(EleveRepository $r) {
								// return $r->getElevesByAlphabeticalOrder();
							// },
						// 'attr' => array('class'=>'form-control')
						// ),
					// 'allow_add' => true,
					// 'allow_delete' => true,
					// 'required' => false,
					// 'by_reference' => false
					// ))
        ;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Majordesk\AppBundle\Entity\Professeur'
		));
    }

    public function getName()
    {
        return 'professeurtype';
    }
}

src/Majordesk/AppBundle/Resources/views/Professeur/declarer-cours.html.twig
{% extends "::layout.html.twig" %}

{% block title %}
	Déclaration du cours - {{ parent() }}
{% endblock %}

{% block navbar %}
	<li><a><i class="icon-angle-right"></i> Déclaration du cours</a></li>
{% endblock %}

{% block body %}
		<span class="visible-md"><br></span>
		<span class="visible-lg"><br></span>	
		{% for message in app.session.flashbag.get('info') %}
			<div class="alert alert-success">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				<i class="icon-info-sign"></i> <strong>Info :</strong> {{ message }}
			</div>
		{% endfor %}
		{% for message in app.session.flashbag.get('warning') %}
			<div class="alert alert-danger">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				<i class="icon-warning-sign"></i> <strong>Erreur :</strong> {{ message }}
			</div>
		{% endfor %}
		<div class="clearfix"></div>
		{% if prelevementCours != 1 %}
		<div class="alert alert-info">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<i class="icon-info-sign"></i> <strong>Info :</strong> 
			Le crédit restant d'heures de cours est de <strong>{{ heuresRestantes / 10 }}h</strong>.
		</div>
		{% endif %}
			<br>
			<strong>Déclaration du cours</strong><br><br>

		
		{% if no_calevent_message %}
			<em>Pour déclarer un cours, il faut qu'il apparaisse dans le calendrier.<br>
			Il est possible de déclarer un cours lorsque son heure de début est située dans un créneau allant de "il y a 5 heures" à "dans 1 heure".</em><br><br>
		{% else %}
			<form class="form-horizontal" action="{{ path('majordesk_app_declarer_cours', { 'id_matiere' : id_matiere }) }}" method="post" role="form">
				<div class="col-lg-4">
					<div class="form-group">
					{{ form_widget(form.cal_event) }}
					</div>
				</div>
				<div class="col-lg-5">
					<div class="form-group">
						<div class="col-lg-8 control-label">
							Durée effective du cours :
						</div>
						<div class="col-lg-4">
						{{ form_widget(form.quantite) }}
						</div>
					</div>
				</div>
				{% if filtre %}
				<div class="col-lg-3">
					<div class="form-group">
						{{ form_widget(form.passparent) }}
					</div>
				</div>
				{% endif %}
				<span class="pull-right">
					<button type="submit" class="btn btn-primary">Déclarer ce cours <i class="icon-angle-right"></i></button>
				</span>
			{{ form_widget(form._token) }}
			</form>
			<div class="clearfix"></div>
			<br>
		{% endif %}
{% endblock %}

src/Majordesk/AppBundle/Resources/views/Professeur/gestion-devoirs.html.twig
{% extends "::layout.html.twig" %}

{% block title %}
	{% if is_granted('ROLE_PROF') %}
		Gestion des devoirs et exercices faits
	{% elseif is_granted('ROLE_PARENTS') %}
		Suivi de votre enfant
	{% elseif is_granted('ROLE_ELEVE') and not is_granted('ROLE_PROF') %}
		Vérification des devoirs
	{% endif %}
	 - {{ parent() }}
{% endblock %}

{% block navbar %}
	{% if is_granted('ROLE_ADMIN') %}
		<li><a href="{{ path("majordesk_app_gestion_eleves") }}"><i class="icon-angle-right"></i> Gestion des élèves</a></li>
	{% endif %}
	{% if is_granted('ROLE_ADMIN') %}
		<li><a><i class="icon-angle-right"></i> Déblocage d'un élève</a></li>
	{% elseif is_granted('ROLE_PROF') %}
		<li><a><i class="icon-angle-right"></i> Gestion des devoirs et exercices faits</a></li>
	{% elseif is_granted('ROLE_PARENTS') %}
		<li><a><i class="icon-angle-right"></i> Suivi de votre enfant</a></li>
	{% elseif is_granted('ROLE_ELEVE') and not is_granted('ROLE_PROF') %}
		<li><a><i class="icon-angle-right"></i> Vérification des devoirs</a></li>
	{% endif %}
{% endblock %}

{% block body %}
		<br><br><br><span class="visible-xs"><br></span>
		
		{% if not is_granted('ROLE_ADMIN') and is_granted('ROLE_PROF') %}
		<div class="col-lg-12">
			<a class="btn btn-default" disabled>{{ eleve.username }} {{ eleve.nom }}</a> 
			{% for elv in eleves if elv.id != eleve.id %}
				<a href="{{ path('majordesk_app_gestion_devoirs', {'id_eleve' : elv.id }) }}" class="btn btn-default">{{ elv.username }} {{ elv.nom }}</a> 
			{% endfor %}
			<span class="pull-right">Total : <span class="badge">{{ exercices|length }}</span></span>
		</div>
		<br>
		{% endif %}
		
		{% if is_granted('ROLE_PARENTS') %}
		<div class="col-lg-12">
			<h3>Cette semaine :</h3><br>
		</div>
		<div class="col-lg-4">
			<div id="id-eleve" data-id-eleve="{{ eleve.id }}"></div>
			<br>
			Temps total travaillé : <strong id="temps-week"><i class="icon-spinner icon-spin"></i></strong>
			<br><br>
			Nombre d'exercices faits : <strong id="ex-faits"><i class="icon-spinner icon-spin"></i></strong>
			<br><br>
			Nombre d'exercices validés : <strong id="ex-valides"><i class="icon-spinner icon-spin"></i></strong>
			<br><br>
			Nombre moyen d'essais par question : <strong id="nb-moyen"><i class="icon-spinner icon-spin"></i></strong>
			<br><br>	
		</div>
		<div class="col-lg-4">
			<div id="graph_semaine_exercices" style="height:200px;" ></div>
		</div>
		<div class="col-lg-4">
			<div id="graph_semaine_autonomie" style="height:200px;" ></div>
		</div>
		<div class="clearfix"></div><br>
		<div class="col-lg-12">
			<h3>Liste des exercices faits depuis le dernier cours</h3><br>
		</div>
		{% endif %}
		
		{% if not is_granted('ROLE_PROF') and not is_granted('ROLE_PARENTS') and is_granted('ROLE_ELEVE') %}
		<div class="col-lg-6">
			<strong>Exercices faits depuis le dernier cours :</strong><br><br>
			<ul>
				<li>Vérifier que les devoirs <i class="icon-bullseye text-blue" rel="tooltip" data-title="Devoir à faire"></i> ont bien été faits</li>
				<li>Travailler les exercices mis de côté <i class="icon-star text-yellow" rel="tooltip" data-title="Mis de côté"></i> et non résolus <i class="icon-remove text-red" rel="tooltip" data-title="En cours..."></i></li>
			</ul>
		</div>
		<div class="col-lg-6">
			<a href="{{ path('majordesk_app_recherche_exercices', {'id_matiere' : app.session.get('matiere_cours') }) }}" class="btn btn-primary pull-right">Passer à l'entrainement <i class="icon-angle-right"></i></a>
			<br><br><br>
			<span class="pull-right"><strong>Temps total : </strong> {{ temps_total|date('G\\h i\\m\\i\\n s\\s') }}</span>
		</div>
		<div class="clearfix"></div>
		<br>
		{% endif %}
		<div class="col-lg-12">
			<div class="table-responsive">
				<table class="table table-bordered table-hover">
					<thead>
						<tr>
							<th>Statut</th>
							<th><i class="icon-eye-open"></i></th>
							<th>Chapitre</th>
							<th>Partie</th>
							<th>Niv.</th>
							<th style="width:100px;">Essai(s)</th>
							<th style="width:100px;">Temps</th>
							<th style="width:80px;">Date</th>
							{% if is_granted('ROLE_ADMIN') %}
								<th style="width:100px;">Réinit</th>
							{% endif %}
						</tr>
					</thead>
					<tbody>
						{% for exercice in exercices %}
						<tr>
							<td>
								{% if exercice.statut == statut_resolu %}
									<i class="icon-ok text-success" rel="tooltip" data-title="Terminé"></i> 
								{% elseif exercice.statut == statut_non_resolu %}
									<i class="icon-remove text-red" rel="tooltip" data-title="En cours..."></i>
								{% else %}
									<i class="icon-remove text-light-grey" rel="tooltip" data-title="Non commencé"></i>
								{% endif %}
								{% if exercice.favoris %}
									<i class="icon-star text-yellow" rel="tooltip" data-title="Mis de côté"></i>
								{% endif %}
								{% if exercice.selection %}
									<i class="icon-bullseye text-blue" rel="tooltip" data-title="Devoir à faire"></i>
								{% endif %}
							</td>
							<td> {% if exercice.modExercice.statut == statut_en_ligne %}<a href="{{ path('majordesk_app_exercice', {'id_exercice' : exercice.id }) }}" rel="tooltip" data-title="Voir l'énoncé"><i class="icon-external-link"></i></a>{% else %}<i class="icon-external-link" rel="tooltip" data-title="Exercice en maintenance"></i>{% endif %} </td>
							<td>{{ exercice.modExercice.chapitre.nom }}</td>
							<td>{{ exercice.modExercice.partie.nom|raw }}</td>
							<td>{{ exercice.modExercice.niveau }}</td>
							<td>{% if exercice.getNombreEssais > 2.9*exercice.getNombreQuestionsCommencees(statut_non_commence) %}<span class="text-red">{% endif %}{{ exercice.getNombreEssais }}{% if exercice.getNombreEssais >= 3*exercice.getNombreQuestionsCommencees(statut_non_commence) %}</span>{% endif %} sur {{ exercice.getNombreQuestionsCommencees(statut_non_commence) }} q°</td>
							<td>{{ exercice.temps|date("i\\m\\i\\n s\\s") }}</td>
							<td>{{ exercice.getDerniereDate|date("d/m/y \\à G:i")}}</td>
							{% if is_granted('ROLE_ADMIN') %}
								<td data-id-exercice="{{ exercice.id }}"><button rel="tooltip" data-title="Remettre à zéro" data-placement="right" class="btn btn-default reinit" type="button"><i class="icon-refresh"></i></button> <a href="{{ path('majordesk_app_deblocage_remove', { 'id_exercice' : exercice.id, 'id_eleve' : exercice.eleve.id }) }}" rel="tooltip" data-message="Voulez-vous supprimer définitivement cet exercice ?" data-title="Supprimer" data-placement="right" class="btn btn-default dump confirm-majorclass" type="button"><i class="icon-trash"></i></a></td>
							{% endif %}
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
			{% if not is_granted('ROLE_ADMIN') and (is_granted('ROLE_PROF') or is_granted('ROLE_PARENTS')) %}
				<span class="pull-right"><strong>Temps total : </strong> {{ temps_total|date('G\\h i\\m\\i\\n s\\s') }}</span>
			{% endif %}
		</div>
		
		{% if is_granted('ROLE_PARENTS') %}
		<div class="clearfix"></div><br>
		<div class="col-lg-12">
			<h3>Ce mois :</h3><br>
		</div>
		<div class="col-lg-4">
			<div id="id-eleve" data-id-eleve="{{ eleve.id }}"></div>
			<br>
			Temps total travaillé : <strong id="temps-month"><i class="icon-spinner icon-spin"></i></strong>
			<br><br>
			Nombre d'exercices faits : <strong id="ex-faits-month"><i class="icon-spinner icon-spin"></i></strong>
			<br><br>
			Nombre d'exercices validés : <strong id="ex-valides-month"><i class="icon-spinner icon-spin"></i></strong>
			<br><br>
			Nombre moyen d'essais par question : <strong id="nb-moyen-month"><i class="icon-spinner icon-spin"></i></strong>
			<br><br>	
		</div>
		<div class="col-lg-4">
			<div id="graph_mois_exercices" style="height:200px;" ></div>
		</div>
		<div class="col-lg-4">
			<div id="graph_mois_autonomie" style="height:200px;" ></div>
		</div>
		<div class="clearfix"></div><br>
		{% endif %}
{% endblock %}

{% block javascripts %}
	{{ parent() }}
	{% if is_granted('ROLE_ADMIN') %}
		{% javascripts filter='yui_js' output='js/*'  
			'../app/Resources/js/professeur/gestion-devoirs.js' 
		%}
			<script type="text/javascript" src="{{ asset_url }}"></script>
		{% endjavascripts %}
	{% elseif not is_granted('ROLE_ADMIN') and is_granted('ROLE_PARENTS') %}
		{% javascripts filter='yui_js' output='js/*' 
			'../app/Resources/js/common/highcharts.js' 
			'../app/Resources/js/parents/suivi-enfant.js' 
		%}
			<script type="text/javascript" src="{{ asset_url }}"></script>
		{% endjavascripts %}
	{% endif %}
{% endblock %}