src/Majordesk/AppBundle/Entity/Partie.php
<?php

namespace Majordesk\AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Partie
 *
 * @ORM\Table(name="partie")
 * @ORM\Entity(repositoryClass="Majordesk\AppBundle\Entity\PartieRepository")
 */
class Partie
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=255)
     */
    private $nom;
	
	/**
     * @var integer
     *
     * @ORM\Column(name="numero", type="smallint")
     */
    private $numero;
	
	/**
	* @ORM\OneToMany(targetEntity="Majordesk\AppBundle\Entity\ModExercice", mappedBy="partie", cascade={"remove"})
	*/
	private $mod_exercices;
	
	/**
	* @ORM\ManyToOne(targetEntity="Majordesk\AppBundle\Entity\Chapitre", inversedBy="parties")
	*/
	private $chapitre;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nom
     *
     * @param string $nom
     * @return Partie
     */
    public function setNom($nom)
    {
        $this->nom = $nom;
    
        return $this;
    }

    /**
     * Get nom
     *
     * @return string 
     */
    public function getNom()
    {
        return $this->nom;
    }
	
	/**
     * Get numero
     *
     * @return integer 
     */
    public function getNumero()
    {
        return $this->numero;
    }

    /**
     * Set numero
     *
     * @param integer $numero
     * @return Chapitre
     */
    public function setNumero($numero)
    {
        $this->numero = $numero;
    
        return $this;
    }
    
    /**
     * Add mod_exercices
     *
     * @param \Majordesk\AppBundle\Entity\ModExercice $modExercice
     * @return Partie
     */
    public function addModExercice(\Majordesk\AppBundle\Entity\ModExercice $modExercice)
    {
        $this->mod_exercices[] = $modExercice;
    
        return $this;
    }

    /**
     * Remove mod_exercices
     *
     * @param \Majordesk\AppBundle\Entity\ModExercice $modExercice
     */
    public function removeModExercice(\Majordesk\AppBundle\Entity\ModExercice $modExercice)
    {
        $this->mod_exercices->removeElement($modExercice);
    }

    /**
     * Get mod_exercices
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getModExercices()
    {
        return $this->mod_exercices;
    }

    /**
     * Set chapitre
     *
     * @param \Majordesk\AppBundle\Entity\Chapitre $chapitre
     * @return Partie
     */
    public function setChapitre(\Majordesk\AppBundle\Entity\Chapitre $chapitre = null)
    {
        $this->chapitre = $chapitre;
    
        return $this;
    }

    /**
     * Get chapitre
     *
     * @return \Majordesk\AppBundle\Entity\Chapitre 
     */
    public function getChapitre()
    {
        return $this->chapitre;
    }
	
	/**
     * Constructor
     */
    public function __construct()
    {
        $this->mod_exercices = new \Doctrine\Common\Collections\ArrayCollection();
    }
}

src/Majordesk/AppBundle/Form/Type/EleveType.php
<?php

namespace Majordesk\AppBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class EleveType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('mail'                , 'email', array(
				'attr' => array('class'=>'form-control')
				))
            // ->add('password'            , 'password')
            // ->add('salt')
            // ->add('roles')
            ->add('username'              , 'text', array(
				'attr' => array('class'=>'form-control')
				))
            ->add('nom'                 , 'text', array(
				'attr' => array('class'=>'form-control')
				))
            // ->add('actif')
            // ->add('flag')
			->add('programme'       , 'entity', array(
					'class' => 'MajordeskAppBundle:Programme',
					'property' => 'nom',
					'empty_value' => 'Choisir un programme',
					'attr' => array('class'=>'form-control')
					))
            ->add('lycee'               , 'text', array(
				'required' => false,
				'attr' => array('class'=>'form-control')
				))
            ->add('telephone'           , 'text', array(
				'required' => false,
				'attr' => array('class'=>'form-control')
				))
            ->add('heures_prises'       , 'integer', array(
				'attr' => array('class'=>'form-control')
				))
            ->add('notifications'       , 'integer', array(
				'attr' => array('class'=>'form-control')
				))
            ->add('rythme'              , 'integer', array(
				'attr' => array('class'=>'form-control')
				))
            ->add('date_inscription'    , 'date', array(
				'widget' => 'single_text',
				'format' => 'dd/MM/yyyy',
				'attr' => array('class' =>'form-control datepicker'),
				'invalid_message' => 'La date entrée est incorrecte'
				))
			// ->add('date_abonnement'    , 'date', array(
				// 'widget' => 'single_text',
				// 'format' => 'dd/MM/yyyy',
				// 'attr' => array('class' =>'form-control datepicker'),
				// 'invalid_message' => 'La date entrée est incorrecte'
				// ))
			// ->add('situation'         , 'choice', array(
				// 'choices' => array('0' => 'Aucune', '1' => 'Plateforme', '2' => 'Cours', '3' => 'Cours et Plateforme'),
				// 'attr' => array('class'=>'form-control')
				// ))
			// ->add('autorisation_prelevement'         , 'choice', array(
				// 'choices' => array('0' => 'Non', '1' => 'Oui (Plateforme)', '2' => 'Oui (Cours)', '3' => 'Oui (Cours et Plateforme)'),
				// 'attr' => array('class'=>'form-control')
				// ))
			->add('eleve_matieres'         , 'collection', array(
					'type'         => new EleveMatiereType(),
					'options'      => array(
							'attr' => array('class'=>'form-control')
						),
					'required' => false,
					'allow_add'    => true,
                    'allow_delete' => true,
					'by_reference' => false
					))
			->add('disponibilites', 'collection', array(
					'type'         => new DisponibiliteSansFinType(),
					'required' => false,
					'allow_add'    => true,
                    'allow_delete' => true,
					'by_reference' => false,
					'options'      => array(
							'attr' => array('class'=>'form-control')
						),
					))
            // ->add('famille'             , 'integer')
            // ->add('professeurs'          , 'integer')
        ;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Majordesk\AppBundle\Entity\Eleve'
        ));
    }

    public function getName()
    {
        return 'elevetype';
    }
}

src/Majordesk/AppBundle/Controller/EleveController.php
<?php

namespace Majordesk\AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use JMS\SecurityExtraBundle\Annotation\Secure;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

use Symfony\Component\HttpFoundation\Response;

use Majordesk\AppBundle\Entity\CalEvent;
use Majordesk\AppBundle\Entity\Ticket;
use Majordesk\AppBundle\Entity\Paiement;
use Majordesk\AppBundle\Entity\Exercice;
use Majordesk\AppBundle\Entity\Question;
use Majordesk\AppBundle\Entity\Casier;
use Majordesk\AppBundle\Entity\CarteEtudiant;
use Majordesk\AppBundle\Entity\Contrat;

use Majordesk\AppBundle\Form\Type\CoursType;
use Majordesk\AppBundle\Form\Type\CoursFilterType;
use Majordesk\AppBundle\Form\Type\TicketType;
use Majordesk\AppBundle\Form\Type\TicketNoFiltreType;
use Majordesk\AppBundle\Form\Type\PasswordType;
use Majordesk\AppBundle\Form\Type\ProfInfoType;

class EleveController extends Controller
{

/* INDEX */

	/**
	 * @Secure(roles="ROLE_ELEVE")
	 */
	public function indexEleveAction()
    {
		if ($this->get('security.context')->isGranted('ROLE_ELEVE') && !$this->get('security.context')->isGranted('ROLE_PROF') && !$this->get('security.context')->isGranted('ROLE_PARENTS') && !$this->get('security.context')->isGranted('ROLE_ADMIN')) {
			
			$user = $this->getUser();
			$professeurs = $user->getProfesseurs();
			$famille = $user->getFamille();
			$heuresRestantes = $famille->getHeuresRestantes();
			$filtre = $famille->getFiltre();
			
			$ticket = new Ticket();
			$ticket->setEleve($user);
			if ($filtre) {
				$form = $this->createForm( new TicketType($user->getId()), $ticket );
			} else {
				$form = $this->createForm( new TicketNoFiltreType($user->getId()), $ticket );
			}
			
			$request = $this->getRequest();
			if ($request->getMethod() == 'POST') 
			{
				$form->bind($request);

				if ($form->isValid()) 
				{
					$paymentAuthorized = false;
					if ($filtre) {
						$passparent = $form->get('passparent')->getData();
						$factory = $this->get('security.encoder_factory');
						$parents = $famille->getClients();
						foreach($parents as $parent) {
							$encoder = $factory->getEncoder($parent);			
							$encoded_pass = $encoder->encodePassword($passparent, $parent->getSalt());

							if ($encoded_pass == $parent->getPassword()) {
								$paymentAuthorized = true;
								break;
							}
						}
					}
					
					$eleve = $user;					
					$quantite = $ticket->getQuantite();
					$matiere = $form->get('matiere')->getData();
					
					$eleve_matiere = $this->getDoctrine()
										  ->getManager()
										  ->getRepository('MajordeskAppBundle:EleveMatiere')
										  ->getEleveMatiereByEleveAndMatiere($eleve->getId(), $matiere->getId());
					if (empty($eleve_matiere)) {
						throw new \Exception('eleve_matiere ne devrait pas être null');
					}
					$prelevementCours = $eleve_matiere->getPrelevementCours();
					
					if ($quantite == 10) {
						$temps = '1h';
					} else if ($quantite == 15) {
						$temps = '1h30';
					} else if ($quantite == 20) {
						$temps = '2h';
					} else if ($quantite == 25) {
						$temps = '2h30';
					} else if ($quantite == 30) {
						$temps = '3h';
					} else if ($quantite == 35) {
						$temps = '3h30';
					} else if ($quantite == 40) {
						$temps = '4h';
					} else if ($quantite == 45) {
						$temps = '4h30';
					} else if ($quantite == 50) {
						$temps = '5h';
					} else {
						$temps = 'n.c.';
					}
					$heuresReellesRestantes = $heuresRestantes / 10;
					$heuresIncrementees = $heuresReellesRestantes - $quantite / 10;
					$em = $this->getDoctrine()->getManager();
					
					if ($paymentAuthorized || $filtre == false) {
						$professeur = $ticket->getProfesseur();
						$professeur->setHeuresDonnees($professeur->getHeuresDonnees() + $quantite);
						if ($quantite <= $heuresRestantes) {
							$ticket->setRegle(false);
							$paiement = new Paiement();
							$paiement->setDescription($eleve->getUsername().' a pris un cours de '.$temps.'.<br>Il vous reste <strong>'.$heuresIncrementees.'</strong> heure(s) de cours.');
							$paiement->setFamille($famille);
							$paiement->setPack('1'.$quantite);
							$paiement->setMontant(0);
							$paiement->setTransaction(2);  // 0: annulé, 1: en cours, 2: validé, 3:ticket non réglé
							$paiement->setTicket($ticket);
							
							$famille->setHeuresRestantes($heuresRestantes - $quantite);
							$famille->setHeuresPrises($famille->getHeuresPrises() + $quantite);
							$eleve->setHeuresPrises($eleve->getHeuresPrises() + $quantite);
							$eleve_matiere->setHeuresPrises($eleve_matiere->getHeuresPrises() + $quantite);
							
							$em->persist($eleve_matiere);
							$em->persist($paiement);
							$em->persist($famille);
						}
						else if ($prelevementCours == 1) {
							if ($heuresRestantes > 0) {
								$ticket->setRegle(false);
								
								$famille->setHeuresRestantes(0);
								
								$quantiteRestanteADebiter = $quantite - $heuresRestantes;

								$paiement = new Paiement();
								$paiement->setDescription($eleve->getUsername().' a pris un cours de '.$temps.'.<br>Il vous restait '.$heuresReellesRestantes.' heure(s) qui sont maintenant épuisée(s).<br>Le complément de paiement va être effectué avec votre numéro d\'abonné.');
								$paiement->setFamille($famille);
								$paiement->setPack('2'.$quantiteRestanteADebiter);
								$paiement->setMontant(599.0*$quantiteRestanteADebiter);
								$paiement->setTransaction(1);
								$paiement->setTicket($ticket);
								
								$famille->setHeuresAchetees($famille->getHeuresAchetees() + $quantiteRestanteADebiter);
								$famille->setHeuresPrises($famille->getHeuresPrises() + $quantite);
								$eleve->setHeuresPrises($eleve->getHeuresPrises() + $quantite);
								$eleve_matiere->setHeuresPrises($eleve_matiere->getHeuresPrises() + $quantite);
								
								$em->persist($eleve_matiere);
								$em->persist($paiement);
								$em->persist($famille);
							}
							else {
								$ticket->setRegle(false);
							
								$paiement = new Paiement();
								$paiement->setDescription($eleve->getUsername().' a pris un cours de '.$temps.'.');
								$paiement->setFamille($famille);
								$paiement->setPack('2'.$quantite);
								$paiement->setMontant(599.0*$quantite);
								$paiement->setTransaction(1);
								$paiement->setTicket($ticket);
								
								$famille->setHeuresAchetees($famille->getHeuresAchetees() + $quantite);
								$famille->setHeuresPrises($famille->getHeuresPrises() + $quantite);
								$eleve->setHeuresPrises($eleve->getHeuresPrises() + $quantite);
								$eleve_matiere->setHeuresPrises($eleve_matiere->getHeuresPrises() + $quantite);
								
								$em->persist($eleve_matiere);
								$em->persist($paiement);
								$em->persist($famille);
							}
						}
						else {
							$ticket->setRegle(false);
							
							$paiement = new Paiement();
							$paiement->setDescription($eleve->getUsername().' a pris un cours de '.$temps.'.<br>Il ne vous reste pas suffisamment d\'heures pour payer ce cours.<br><strong>Veuillez recréditer votre compte.</strong>');
							$paiement->setFamille($famille);
							$paiement->setPack('3'.$quantite);
							$paiement->setMontant(599.0*$quantite);
							$paiement->setTransaction(3);
							$paiement->setTicket($ticket);
							
							$famille->setHeuresRestantes($heuresRestantes - $quantite);
							$famille->setHeuresPrises($famille->getHeuresPrises() + $quantite);
							$eleve->setHeuresPrises($eleve->getHeuresPrises() + $quantite);
							$eleve_matiere->setHeuresPrises($eleve_matiere->getHeuresPrises() + $quantite);
							
							$em->persist($eleve_matiere);
							$em->persist($paiement);
							$em->persist($famille);
						}
						
						$em->persist($ticket);
						$em->persist($professeur);
						
						$em->flush();
						$this->get('session')->getFlashBag()->add('info', ' Le cours a bien été déclaré.');
						return $this->redirect($this->generateUrl('majordesk_app_index_eleve'));
					}
					else {
						$session->getFlashBag()->add('warning', ' Mot de passe du parent incorrect.');
					}
				}
				else {
					// $errors = $form->getErrorsAsString();
					$this->get('session')->getFlashBag()->add('warning', ' Un ou plusieurs champs ont été mal remplis.');
				}
			}
			}
			
			return $this->render('MajordeskAppBundle:Eleve:index-eleve.html.twig', array(
				'form' => $form->createView(),
				'professeurs' => $professeurs,
				'famille' => $famille,
			));
	}
	
	/**
	 * @Secure(roles="ROLE_ELEVE")
	 */
    public function recommandezNousAction()
    {
		$user = $this->getUser();	
		if ($this->get('security.context')->isGranted('ROLE_ELEVE') && !$this->get('security.context')->isGranted('ROLE_PROF') && !$this->get('security.context')->isGranted('ROLE_PARENTS') && !$this->get('security.context')->isGranted('ROLE_ADMIN')) {
			$defaultData = array('destinataire'=>'', 'corps' => "Salut,\n\nSi tu cherches un bon prof particulier, je te recommande Majorclass !\n\nPersonnellement il m'ont vraiment aidé. Leur site est : www.majorclass.fr\n\nA plus!");
		} else {
			$defaultData = array('destinataire'=>'', 'corps' => "Bonjour,\n\nSi vous cherchez un professeur particulier de qualité pour votre enfant, en Mathématiques ou Physique/Chimie, Majorclass est ce qu'il vous faut !\n\nLeurs professeurs sont sélectionnés parmi des étudiants de Grandes Ecoles expérimentés et je suis pour ma part très satisfait(e) de la qualité de leurs services.\n\nJe vous les recommande vivement. Leur site est www.majorclass.fr.\n\nA bientôt!");
		}
		
		$form = $this->createFormBuilder($defaultData)
							->add('destinataire', 'email', array(

src/Majordesk/AppBundle/Resources/views/Eleve/consulter-fiches.html.twig
{% extends "::layout.html.twig" %}

{% block title %}
	Fiches de cours
{% endblock %}

{% block navbar %}
		<li><a><i class="icon-angle-right"></i> Fiches de cours</a></li>
{% endblock %}

{% block body %}
		<span class="visible-md"><br></span>
		<span class="visible-lg"><br></span>

			<h3><i class="icon-paper-clip icon-large text-grey"></i> Fiches de cours</h3><br>
			
			{% for matiere in app.user.matieres %}
			{% if matiere.nom == matiere_mathematiques %}
				<span class="label label-info">{{ matiere_mathematiques }}</span><br><br>
				<div class="table-responsive">
					<table class="table table-bordered table-hover">
						<thead>
							<tr>
								<th>Chapitre</th>
								<th><div class="text-center">Fiches</div></th>
							</tr>
						</thead>
						<tbody>
							{% for chapitre in app.user.programme.chapitres %}
							<tr>
								<td>{{ chapitre.nom }}</td>
								<td><div class="text-center"><a href="{{ path('majordesk_app_afficher_fiche', { 'id_matiere' : matiere.id, 'id_programme' : app.user.programme.id , 'chapitre' : chapitre.numero}) }}"><i class="icon-external-link"></i></a></div></td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
				<br>
				{% elseif matiere.nom == matiere_physique %}
				<span class="label label-success">{{ matiere_physique }}</span><br><br>
				<em>Aucune fiche pour l'instant</em>
				{% endif %}
			{% else %}
				<em>Aucune fiches pour l'instant</em>
			{% endfor %}
			<br>
{% endblock %}

{% block javascripts %}
	{{ parent() }}
{% endblock %}

src/Majordesk/AppBundle/Resources/views/Eleve/consulter-resumes.html.twig
{% extends "::layout.html.twig" %}

{% block title %}
	Résumés de cours
{% endblock %}

{% block navbar %}
		<li><a><i class="icon-angle-right"></i> Résumés de cours</a></li>
{% endblock %}

{% block body %}
		<span class="visible-md"><br></span>
		<span class="visible-lg"><br></span>

			<h3><i class="icon-file-text-alt icon-large text-light-blue"></i> Résumés de cours</h3><br>
			
			{% for matiere in app.user.matieres %}
				{% if matiere.nom == matiere_mathematiques %}
				<span class="label label-info">{{ matiere_mathematiques }}</span><br><br>
				<div class="table-responsive">
					<table class="table table-bordered table-hover">
						<thead>
							<tr>
								<th>Chapitre</th>
								<th><div class="text-center">Résumé de cours</div></th>
							</tr>
						</thead>
						<tbody>
							{% for chapitre in app.user.programme.chapitres %}
							<tr>
								<td>{{ chapitre.nom }}</td>
								<td><div class="text-center"><a href="{{ path('majordesk_app_afficher_resume', { 'id_chapitre' : chapitre.id }) }}"><i class="icon-eye-open"></i></a></div></td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
				<br>
				{% elseif matiere.nom == matiere_physique %}
				<span class="label label-success">{{ matiere_physique }}</span><br><br>
				<em>Aucune résumé de cours pour l'instant</em>
				{% endif %}
			{% else %}
				<em>Aucune résumé de cours pour l'instant</em>
			{% endfor %}
			<br>
{% endblock %}

{% block javascripts %}
	{{ parent() }}
{% endblock %}

src/Majordesk/AppBundle/Resources/views/Eleve/eleve-parties.html.twig
{% extends "MajordeskAppBundle:Eleve:navigation.html.twig" %}

{% block title %}
	Liste des parties - {{ parent() }}
{% endblock %}

{% block navbar %}
	<li><a href="{{ path("majordesk_app_chapitres") }}"><i class="icon-angle-right"></i> Liste des chapitres</a></li>
	<li><a><i class="icon-angle-right"></i> Liste des exercices</a></li>
{% endblock %}

{% block eleve %}
	{% if is_granted("ROLE_ELEVE") %}
	
		<span class="visible-md"><br></span>
		<span class="visible-lg"><br></span>
		
		{% for message in app.session.flashbag.get('info') %}	
		<div class="col-lg-12">
			<div class="alert alert-success">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				{{ message }}
			</div>
		</div>
		{% endfor %}
		
		<div class="col-lg-12">
			<h3><i class="icon-book icon-large text-red pull-left"></i> {{ chapitre.nom }}</h3><br>
		</div>
		<div class="col-lg-6">
			<div class="panel panel-default">
				<div class="panel-heading"><strong>Parties</strong></div>
				<div class="list-group accordion" id="collapsible-parties">
					{% for partie in parties %}
						{% set isVide = 0 %}
						{% for modExercice in partie.modExercices if modExercice.statut == statut_en_ligne %}
							{% set isVide = isVide + 1 %}
						{% endfor %}
					<a class="list-group-item partie cursor" data-id="{{ partie.id }}" data-vide="{{ isVide }}" data-toggle="collapse" data-target="#partie_{{ loop.index }}" data-parent="#collapsible-parties">{{ partie.numero }}. {{ partie.nom|raw }} <span class="pull-right"><i class="icon-chevron-right"></i></span></a>
					<div class="hide">{{ partie.nom|raw }}</div>
					<div class="accordion-group">
						<div id="partie_{{ loop.index }}" class="collapse">
						  <div class="container">
							<br>
							<div class="col-lg-6">
								<div class="blockprof">
									{% for exercice in exercices if exercice.modExercice.partie == partie and not exercice.autonomie %}
										<span class="partie-partie">
											{% if exercice.modExercice.statut != statut_en_ligne %}
												<i class="icon-exclamation-sign text-grey" rel="tooltip" data-title="Exercice en maintenance"></i> 
												<span class="text-grey">Exercice {{ loop.index }}</span>
											{% else %}
												{% if exercice.statut == statut_resolu %}
													<i class="icon-ok text-success" rel="tooltip" data-title="Terminé"></i> 
												{% elseif exercice.statut == statut_non_resolu %}
													<i class="icon-remove text-red" rel="tooltip" data-title="En cours..."></i>
												{% else %}
													<i class="icon-remove text-light-grey" rel="tooltip" data-title="Non commencé"></i>
												{% endif %}
												<a href="{{ path('majordesk_app_exercice', {'id_exercice' : exercice.id }) }}">Exercice {{ loop.index }}</a> 
											{% endif %}
										</span>
									{% else %}
										Aucun exercice fait avec ton professeur dans cette partie pour l'instant.
									{% endfor %}
								</div>
							</div>
							<br><br>
							<div class="col-lg-6">
								<div class="blockauton">
									{% for exercice in exercices if exercice.modExercice.partie == partie and exercice.autonomie %}
										<span class="partie-partie">
											{% if exercice.modExercice.statut != statut_en_ligne %}
												<i class="icon-exclamation-sign text-grey" rel="tooltip" data-title="Exercice en maintenance"></i> 
												<span class="text-grey">Exercice {{ loop.index }}</span>
											{% else %}
												{% if exercice.statut == statut_resolu %}
													<i class="icon-ok text-success" rel="tooltip" data-title="Terminé"></i> 
												{% elseif exercice.statut == statut_non_resolu %}
													<i class="icon-remove text-red" rel="tooltip" data-title="En cours..."></i>
												{% else %}
													<i class="icon-remove text-light-grey" rel="tooltip" data-title="Non commencé"></i>
												{% endif %}
												<a href="{{ path('majordesk_app_exercice', {'id_exercice' : exercice.id }) }}">Exercice {{ loop.index }}</a> 
											{% endif %}
										</span>
									{% else %}
										Aucun exercice fait en autonomie dans cette partie pour l'instant
									{% endfor %}
								</div>
							</div>
						  </div>
						</div>
					</div>
					{% else %}
						Ce chapitre ne contient visiblement aucune partie pour l'instant !
					{% endfor %}
				</div>
			</div>
		</div>
		{% if parties|length != 0 %}
		<div class="col-lg-6" id="partie-stats">
			<div class="panel panel-default">
				<div class="panel-body">
					<i class="icon-info-sign icon-4x text-light-grey pull-left"></i><hr><hr>
				</div>
			</div>
		</div>
		{% endif %}
		<div id="id-eleve" class="hide">{{ app.user.id }}</div>
	{% endif %}
{% endblock %}

{% block javascripts %}
	{{ parent() }}
	{% javascripts filter='yui_js' output='js/*' 
		'../app/Resources/js/eleve/eleve-parties.js' 	
	%}
		<script type="text/javascript" src="{{ asset_url }}"></script>
	{% endjavascripts %}
{% endblock %}

src/Majordesk/AppBundle/Resources/views/Eleve/modifier-password.html.twig
{% extends "::layout.html.twig" %}

{% block title %}
	Abonnements et factures - {{ parent() }}
{% endblock %}

{% block navbar %}
	{% if is_granted('ROLE_PARENTS') and not is_granted('ROLE_ADMIN') %}
		<li><a tabindex="-1" href="{{ path('majordesk_app_abonnements_factures') }}">Mon Compte</a></li>
	{% else %}
		<li><a tabindex="-1" href="{{ path('majordesk_app_profil') }}">Profil</a></li>
	{% endif %}
	<li><a><i class="icon-angle-right"></i> Modifier mon mot de passe</a></li>
{% endblock %}

{% block body %}
<br><br><br>
	
	{% for message in app.session.flashbag.get('warning') %}
	<div class="col-lg-12">
		<div class="alert alert-danger">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<i class="icon-warning-sign"></i> <strong>Demande rejetée :</strong> {{ message }}
		</div>
	</div>
	{% endfor %}
	<div class="col-lg-12">
		<h3>Modifier son mot de passe</h3><br>
	</div>
	<div class="col-lg-4">
		<form class="form-inline" method="post" action="{{ path('majordesk_app_modifier_password') }}">
			Ancien mot de passe :<br>
			{{ form_widget(form.oldpass) }}<br><br>
			Nouveau mot de passe :<br>
			{{ form_widget(form.newpass.pass) }}<br><br>
			Confirmation :<br>
			{{ form_widget(form.newpass.confirm) }}
			<br><br>
			<button type="submit" class="btn btn-success"><i class="icon-ok"></i> Valider</button>
		{{ form_widget(form._token) }}
		</form>
	</div>
	<div class="clearfix"></div><br><br>

{% endblock %}

src/Majordesk/AppBundle/Resources/views/Eleve/navigation-preview.html.twig
{% extends "::layout-preview.html.twig" %}

{% block body %}
	{% block eleve %}
	{% endblock %}
{% endblock %}

