src/Majordesk/AppBundle/Entity/Matiere.php
<?php

namespace Majordesk\AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Matiere
 *
 * @ORM\Table(name="matiere")
 * @ORM\Entity(repositoryClass="Majordesk\AppBundle\Entity\MatiereRepository")
 */
class Matiere
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=255)
     */
    private $nom;
	
	/**
	* @ORM\OneToMany(targetEntity="Majordesk\AppBundle\Entity\ModExercice", mappedBy="matiere")
	*/
	private $mod_exercices;
	
	/**
	 * @ORM\OneToMany(targetEntity="Majordesk\AppBundle\Entity\EleveMatiere", mappedBy="matiere", cascade={"persist"})
	 */
	private $eleve_matieres;
	
	/**
	* @ORM\ManyToMany(targetEntity="Majordesk\AppBundle\Entity\Professeur", mappedBy="matieres")
	*/
	private $professeurs;
	
	/**
	* @ORM\OneToMany(targetEntity="Majordesk\AppBundle\Entity\Tag", mappedBy="matiere", cascade={"persist"})
	*/
	private $tags;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nom
     *
     * @param string $nom
     * @return Matiere
     */
    public function setNom($nom)
    {
        $this->nom = $nom;
    
        return $this;
    }

    /**
     * Get nom
     *
     * @return string 
     */
    public function getNom()
    {
        return $this->nom;
    }
  
    
    /**
     * Add mod_exercices
     *
     * @param \Majordesk\AppBundle\Entity\ModExercice $modExercice
     * @return Matiere
     */
    public function addModExercice(\Majordesk\AppBundle\Entity\ModExercice $modExercice)
    {
        $this->mod_exercices[] = $modExercice;
    
        return $this;
    }

    /**
     * Remove mod_exercices
     *
     * @param \Majordesk\AppBundle\Entity\ModExercice $modExercice
     */
    public function removeModExercice(\Majordesk\AppBundle\Entity\ModExercice $modExercice)
    {
        $this->mod_exercices->removeElement($modExercice);
    }

    /**
     * Get mod_exercices
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getModExercices()
    {
        return $this->mod_exercices;
    }
	
	/**
     * Add eleve_matiere
     *
     * @param \Majordesk\AppBundle\Entity\EleveMatiere $eleve_matiere
     * @return Eleve
     */
    public function addEleveMatiere(\Majordesk\AppBundle\Entity\EleveMatiere $eleve_matiere)
    {
		$this->eleve_matieres[] = $eleve_matiere;
		$eleve_matiere->setMatiere($this);
			
        return $this;
    }

    /**
     * Remove eleve_matiere
     *
     * @param \Majordesk\AppBundle\Entity\EleveMatiere $eleve_matiere
     */
    public function removeEleveMatiere(\Majordesk\AppBundle\Entity\EleveMatiere $eleve_matiere)
    {
        $this->matieres->removeElement($eleve_matiere);
    }

    /**
     * Get matieres
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getEleveMatieres()
    {
        return $this->eleve_matieres;
    }
	
	/**
     * Get eleves
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getEleves()
    {
		$eleves = array();
		foreach($this->eleve_matieres as $eleve_matiere) {
			$eleves[] = $eleve_matiere->getEleve();
		}
        return $eleves;
    }
	
	/**
     * Add professeur
     *
     * @param \Majordesk\AppBundle\Entity\Professeur $professeur
     * @return Matiere
     */
    public function addProfesseur(\Majordesk\AppBundle\Entity\Professeur $professeur)
    {
        $this->professeurs[] = $professeur;
    
        return $this;
    }

    /**
     * Remove professeurs
     *
     * @param \Majordesk\AppBundle\Entity\Professeur $professeur
     */
    public function removeProfesseur(\Majordesk\AppBundle\Entity\Professeur $professeur)
    {
        $this->professeurs->removeElement($professeur);
    }

    /**
     * Get professeurs
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getProfesseurs()
    {
        return $this->professeurs;
    }
	
	/**
     * Add tags
     *
     * @param \Majordesk\AppBundle\Entity\Tag $tag
     * @return Tag
     */
    public function addTag(\Majordesk\AppBundle\Entity\Tag $tag)
    {
        $this->tags[] = $tag;
    
        return $this;
    }

    /**
     * Remove tags
     *
     * @param \Majordesk\AppBundle\Entity\Tag $tag
     */
    public function removeTag(\Majordesk\AppBundle\Entity\Tag $tag)
    {
        $this->tags->removeElement($tag);
    }

    /**
     * Get tags
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getTags()
    {
        return $this->tags;
    }
	
	/**
     * Constructor
     */
    public function __construct()
    {
        $this->mod_exercices = new \Doctrine\Common\Collections\ArrayCollection();
    }
}

src/Majordesk/AppBundle/Entity/Ticket.php
<?php

namespace Majordesk\AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Ticket
 *
 * @ORM\Table(name="ticket")
 * @ORM\Entity(repositoryClass="Majordesk\AppBundle\Entity\TicketRepository")
 */
class Ticket
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_cours", type="datetime")
     */
    private $date_cours;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_ticket", type="datetime")
     */
    private $date_ticket;

    /**
     * @var string
     *
     * @ORM\Column(name="statut", type="string", length=1)
     */
    private $statut;
	
	/**
     * @var string
     *
     * @ORM\Column(name="regle", type="boolean")
     */
    private $regle;
	
	 /**
     * @var smallint
     *
     * @ORM\Column(name="quantite", type="smallint")
     */
    private $quantite;
	
	/**
	* @ORM\ManyToOne(targetEntity="Majordesk\AppBundle\Entity\Eleve", inversedBy="tickets")
	* @ORM\JoinColumn(nullable=false)
	*/
	private $eleve;
	
	/**
	* @ORM\ManyToOne(targetEntity="Majordesk\AppBundle\Entity\Professeur", inversedBy="tickets")
	* @ORM\JoinColumn(nullable=false)
	*/
	private $professeur;
	
	/**
	* @ORM\OneToOne(targetEntity="Majordesk\AppBundle\Entity\Paiement", mappedBy="ticket", cascade={"remove"})
	*/
	private $paiement;
	
	/**
	* @ORM\OneToOne(targetEntity="Majordesk\AppBundle\Entity\CalEvent", mappedBy="ticket")
	*/
	private $cal_event;
	


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set date_cours
     *
     * @param \DateTime $dateCours
     * @return Ticket
     */
    public function setDateCours($dateCours)
    {
        $this->date_cours = $dateCours;
    
        return $this;
    }

    /**
     * Get date_cours
     *
     * @return \DateTime 
     */
    public function getDateCours()
    {
        return $this->date_cours;
    }

    /**
     * Set date_ticket
     *
     * @param \DateTime $dateTicket
     * @return Ticket
     */
    public function setDateTicket($dateTicket)
    {
        $this->date_ticket = $dateTicket;
    
        return $this;
    }

    /**
     * Get date_ticket
     *
     * @return \DateTime 
     */
    public function getDateTicket()
    {
        return $this->date_ticket;
    }

    /**
     * Set statut
     *
     * @param string $statut
     * @return Ticket
     */
    public function setStatut($statut)
    {
        $this->statut = $statut;
    
        return $this;
    }

    /**
     * Get statut
     *
     * @return string 
     */
    public function getStatut()
    {
        return $this->statut;
    }
	
	/**
     * Set regle
     *
     * @param string $regle
     * @return Ticket
     */
    public function setRegle($regle)
    {
        $this->regle = $regle;
    
        return $this;
    }

    /**
     * Get regle
     *
     * @return string 
     */
    public function getRegle()
    {
        return $this->regle;
    }
	
	/**
     * Set quantite
     *
     * @param string $quantite
     * @return Ticket
     */
    public function setQuantite($quantite)
    {
        $this->quantite = $quantite;
    
        return $this;
    }

    /**
     * Get quantite
     *
     * @return string 
     */
    public function getQuantite()
    {
        return $this->quantite;
    }
	
	/**
     * Get montant
     *
     * @return string 
     */
    public function getMontant()
    {
        return $this->quantite * 5.99;
    }
	
	/**
     * Get montant
     *
     * @return string 
     */
    public function getMontantProfesseur()
    {
        return $this->quantite * 2.5;
    }

    /**
     * Set eleve
     *
     * @param \Majordesk\AppBundle\Entity\Eleve $eleve
     * @return Ticket
     */
    public function setEleve(\Majordesk\AppBundle\Entity\Eleve $eleve)
    {
        $this->eleve = $eleve;
    
        return $this;
    }

    /**
     * Get eleve
     *
     * @return \Majordesk\AppBundle\Entity\Eleve 
     */
    public function getEleve()
    {
        return $this->eleve;
    }
	
	/**
     * Set cal_event
     *
     * @param \Majordesk\AppBundle\Entity\CalEvent $cal_event
     * @return Ticket
     */
    public function setCalEvent(\Majordesk\AppBundle\Entity\CalEvent $cal_event)
    {
        $this->cal_event = $cal_event;
		$cal_event->setTicket($this);
    
        return $this;
    }

    /**
     * Get cal_event
     *
     * @return \Majordesk\AppBundle\Entity\CalEvent 
     */
    public function getCalEvent()
    {
        return $this->cal_event;
    }
	
	/**
     * Set paiement
     *
     * @param \Majordesk\AppBundle\Entity\Paiement $paiement
     * @return Eleve
     */
    public function setPaiement(\Majordesk\AppBundle\Entity\Paiement $paiement)
    {
        $this->paiement = $paiement;
    
        return $this;
    }

    /**
     * Get paiement
     *
     * @return \Majordesk\AppBundle\Entity\paiement 
     */
    public function getPaiement()
    {
        return $this->paiement;
    }

    /**
     * Set professeur
     *
     * @param \Majordesk\AppBundle\Entity\Professeur $professeur
     * @return Ticket
     */
    public function setProfesseur(\Majordesk\AppBundle\Entity\Professeur $professeur)
    {
        $this->professeur = $professeur;
    
        return $this;
    }

    /**
     * Get professeur
     *
     * @return \Majordesk\AppBundle\Entity\Professeur 
     */
    public function getProfesseur()
    {
        return $this->professeur;
    }
	
	
	public function __construct()
	{
		$this->date_cours = new \Datetime("now", new \DateTimeZone('Europe/Paris'));
		$this->date_ticket = new \Datetime("now", new \DateTimeZone('Europe/Paris'));
		$this->regle = false;
		$this->statut = '1'; // NON UTILISE. 1: en attente de confirmation du professeur, 2: validé par le professeur, 0: annuler par la famille
	}
}

src/Majordesk/AppBundle/Resources/views/Parents/abonnements-factures.html.twig
{% extends "::layout.html.twig" %}

{% block title %}
	Mon Compte - {{ parent() }}
{% endblock %}

{% block navbar %}
	<li><a><i class="icon-angle-right"></i> Mon Compte</a></li>
{% endblock %}

{% block body %}
<br><br><br>
	
	{% for flashMessage in app.session.flashbag.get('info') %}
		<div class="container">
			<div class="alert alert-info">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				{{ flashMessage|raw }}
			</div>
		</div>
	{% endfor %}

	<div class="col-lg-12">
		<h3>Heures de cours</h3><br>
	</div>
	<div class="col-lg-4">
		Nombre d'heures de cours restantes : <strong>{% if famille.abonnement is empty or famille.heuresRestantes > 0 %}{{ famille.heuresRestantes / 10 }}h{% else %}<span style="font-size:25px;position:relative;top:5px;">&infin;</span>{% endif %}</strong><br><br>
		Nombre total d'heures de cours prises : <strong> {{ famille.heuresPrises / 10 }}h</strong><br><br>
	</div>
	<div class="col-sm-6 col-md-6 col-lg-4">
		<a href="{{ path('majordesk_app_details_heures') }}" class="btn btn-primary-inverted btn-block" ><i class="icon-time icon-4x"></i> <span class="position-relative-up-12">Voir l'historique des paiements</span></a>
	</div>
	<div class="col-sm-6 col-md-6 col-lg-4">
		<a class="btn btn-info-inverted btn-block" href="{{ path('majordesk_app_parametres_compte') }}"><i class="icon-gear icon-4x"></i> <span class="position-relative-up-12">Gérer mon moyen de paiement</span></a>
	</div>
	<div class="clearfix"></div><br>
	
	
	<!--
	<div class="col-lg-12">
		<h3>Abonnements <i class="icon-question-sign cursor" rel="tooltip" data-placement="right" data-title="Notre Plateforme d'entraînement sera lancée pour la rentrée 2014"></i></h3><br>
	</div>
	<div class="clearfix"></div>
	<div class="col-md-6 col-lg-8">
		{% for eleve in eleves %}
			{% for eleve_matiere in eleve.eleveMatieres if eleve_matiere.plateforme == 1 and eleve_matiere.prelevementPlateforme == 1 %}
				<i class="icon-ok icon-large"></i> {{ eleve.username }} est abonné(e) à la Plateforme <span class="label label-info">Mathématiques</span> 
				jusqu'au : {% if eleve_matiere.dateAbonnement != null %}<strong>{{ eleve_matiere.dateAbonnement|date('d/m/Y') }}</strong>{% else %}<em>Non communiqué</em>{% endif %}<br>
				<small><em>date du prochain débit automatique : {% if eleve_matiere.dateAbonnement != null %}{{ eleve_matiere.dateAbonnement|date('d/m/Y') }}{% else %}Non communiquée{% endif %}</em></small><br><br>
			{% else %}
				{{ eleve.username }} : <em>Aucun abonnement pour l'instant</em><br><br>
			{% endfor %}
		{% endfor %}
	</div>
	<div class="col-md-6 col-lg-4">
		<a class="btn btn-info-inverted btn-block inactif" rel="tooltip" data-title="Lancement à la rentrée 2014" href="{#{{ path('majordesk_app_gestion_abonnements') }}#}"><i class="icon-gear icon-4x"></i> <span class="position-relative-up-12">Gérer vos abonnements</span></a>
	</div>
	<div class="clearfix"></div>
	-->
	
	<div class="col-lg-12">
		<h3>Mon Compte</h3><br>
		<strong><i class="icon-user icon-large text-yellow"></i> Mon profil</strong><br><br>
		<div class="col-md-4 col-lg-4">
			Prénom : <strong>{{ app.user.username }}</strong><br>
			Nom : <strong>{{ app.user.nom }}</strong>
		</div>
		<div class="col-md-4 col-lg-4">
			Date d'inscription : <strong>{{ app.user.dateInscription|date('d/m/Y') }}</strong><br>
			Statut : 
			{% if app.user.actif %}
				<strong class="text-green">Actif</strong>
			{% else %}
				<strong class="text-red">Inactif</strong>
			{% endif %}
			<br><br>
		</div>
		<div class="col-md-4 col-lg-4">
			<a href="{{ path('majordesk_app_modifier_password') }}" class="btn btn-default"><i class="icon-gear"></i> Modifier mon mot de passe</a>
		</div>
		<div class="clearfix"></div><br>
		<strong><i class="icon-group icon-large text-greensea"></i> Mes enfants</strong><br><br>
			{% for eleve in eleves %}
				<div class="col-md-4 col-lg-4">
					Prénom : <strong>{{ eleve.username }}</strong><br>
					Nom : <strong>{{ eleve.nom }}</strong>
				</div>
				<div class="col-md-4 col-lg-4">
					Date d'inscription : <strong>{{ eleve.dateInscription|date('d/m/Y') }}</strong><br>
					Statut : 
					{% if eleve.actif %}
						<strong class="text-green">Actif</strong>
					{% else %}
						<strong class="text-red">Inactif</strong>
					{% endif %}
					<br><br>
				</div>
				{% if loop.last %}
					<div class="col-md-4 col-lg-4">
						<a href="{{ path('majordesk_app_nouvel_eleve') }}" class="btn btn-default"><i class="icon-plus"></i> Inscrire un autre enfant</a>
					</div>
				{% else %}
					<div class="clearfix"></div><br>
				{% endif%}
			{% endfor %}	
		<div class="clearfix"></div><br>
		<strong><i class="icon-heart icon-large text-pomegranate"></i> Soutenez-nous</strong><br><br>
		<div class="col-md-8 col-lg-8">
			Notre développement dépend de vos paroles de soutien, alors n'hésitez pas à parler de nous !
			<br><br>
		</div>
		<div class="col-md-4 col-lg-4">
			<a href="{{ path('majordesk_app_soutenez_nous') }}" class="btn btn-default"><i class="icon-thumbs-up"></i> Parler de nous</a>
		</div>
	</div>
	<div class="clearfix"></div><br>
	
	<div class="col-lg-12">
		<h3>Factures</h3><br>
		
		{% if factures is not empty %}
			<ul>
			{% for facture in factures %}
				<li>
					<a href="{{ path('majordesk_app_facture', { 'annee_facture' : facture.dateEmission|date('Y'), 'file_name' : facture.dateEmission|date('Ymd') ~  '-facture-' ~ facture.id }) }}">Facture du {{ facture.dateEmission|date('d/m/Y') }}</a>
				</li>
			{% endfor %}
			</ul>
		{% else %}
			Aucune facture disponible pour l'instant. Leur émission est mensuelle.
		{% endif %}
	</div>
	<div class="clearfix"></div><br>
	<div class="col-lg-12">
		<h3>Impôts</h3><br>
		<strong class="font-majorclass">Majorclass</strong> est un organisme de soutien scolaire agréé (SAP789493467). <br>Conformément à l'article 199 sexdecies du Code Général des Impôts, vous avez droit à une réduction (ou à un crédit) d'impôts à hauteur de 50% des dépenses engagées. 
		<br><br>
		Pour faire valoir votre réduction ou crédit d'impôts, voici un peu d'aide : <a href="{{ path('majordesk_app_aide_impots') }}" class="btn btn-default"><i class="icon-question-sign"></i> Afficher l'aide</a>
	</div>
	<div class="clearfix"></div><br><br>
	

{% endblock %}

{% block javascripts %}
	{{ parent() }}
{% endblock %}

src/Majordesk/AppBundle/Resources/views/Parents/details-heures.html.twig
{% extends "::layout.html.twig" %}

{% block title %}
	Details des heures de cours - {{ parent() }}
{% endblock %}

{% block navbar %}
	<li><a href="{{ path('majordesk_app_abonnements_factures') }}"><i class="icon-angle-right"></i> Mon Compte</a></li>
	<li><a><i class="icon-angle-right"></i> Historique des paiements</a></li>
{% endblock %}

{% block body %}
		<br><br><br>
		
		<div class="col-lg-12">
		<h3>Historique des paiements</h3><br>
		{% if paiements|length > 0 %}
		<div class="table-responsive">
			<table class="table table-hover">
				<thead>
					<tr>
						<th>Date du paiement</th>
						<th>Description</th>
						<th>Montant</th>
						<th>Statut</th>
					</tr>
				</thead>
				<tbody>
				{% for paiement in paiements %}
					<tr>
						<td>{{ paiement.datePaiement|date('d/m/Y') }}</td>
						<td>
							{{ paiement.description|raw }}
						</td>
						<td>
							{% if paiement.pack >= 100 and paiement.pack < 200 %}
								<em>Décompte
								{% if paiement.pack == 110 %}
									1h
								{% elseif paiement.pack == 115 %}
									1h30
								{% elseif paiement.pack == 120 %}
									2h 
								{% elseif paiement.pack == 125 %}
									2h30 
								{% elseif paiement.pack == 130 %}
									3h
								{% elseif paiement.pack == 140 %}
									4h 
								{% elseif paiement.pack == 150 %}
									5h
								{% elseif paiement.pack == 195 %}
								    19.5h
								{% endif %}
								</em>
							{% else %}
								{{ (paiement.montant / 100)|number_format(2, ',', ' ') }} €
							{% endif %}
						</td>
						<td>
							{% if paiement.transaction == 0 %}
								<i rel="tooltip" data-title="Paiement annulé" class="icon-remove text-red cursor-help"></i>
							{% elseif paiement.transaction == 1 %}
								<i rel="tooltip" data-title="Paiement en cours" class="icon-spin icon-spinner text-orange cursor-help"></i>
							{% elseif paiement.transaction == 2 %}
								<i rel="tooltip" data-title="Paiement validé" class="icon-ok text-green cursor-help"></i>
							{% elseif paiement.transaction == 3 %}
								<i rel="tooltip" data-title="Paiement non validé" class="icon-exclamation-sign text-red cursor-help"></i>
							{% else %}
								<i rel="tooltip" data-title="Paiement validé" class="icon-ok text-green cursor-help"></i>
							{% endif %}
						</td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
		</div>
		{% else %}
			Aucun paiement à ce jour.
		{% endif %}
	</div>
	<div class="clearfix"></div><br>
		
		<!--
		<div class="col-lg-12">
			<h3>Détails de heures de cours</h3><br>
		</div>
		{% if tickets|length > 0 %}
		
		<div class="col-lg-12">
			<div class="table-responsive">
				<table class="table table-bordered table-hover">
					<thead>
						<tr>
							<th>Date du cours</th>
							<th>Durée</th>
							<th>Eleve</th>
							<th>Professeur</th>		
						</tr>
					</thead>
					<tbody>
						{% for ticket in tickets %}
						<tr>
							<td>{{ ticket.dateCours|date('d/m/Y') }}</td>
							<td>
								{% if ticket.quantite == 10 %}
									1h
								{% elseif ticket.quantite == 15 %}
									1h30
								{% elseif ticket.quantite == 20 %}
									2h
								{% elseif ticket.quantite == 25 %}
									2h30
								{% elseif ticket.quantite == 30 %}
									3h
								{% elseif ticket.quantite == 40 %}
									4h
								{% elseif ticket.quantite == 50 %}
									5h
								{% elseif ticket.quantite == 195 %}
									19h30
								{% endif %}
							</td>
							<td>{{ ticket.eleve.username }}</td>
							<td>{{ ticket.professeur.username }}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
		
		{#
		<div class="col-lg-12">
			<div class="table-responsive">
				<table class="table table-bordered table-hover">
					<thead>
						<tr>
							<th>Matière</th>
							<th>Date du cours</th>
							<th>Début prévu</th>
							<th>Fin prévue</th>
							<th>Durée effective</th>
							<th>Eleve</th>
							<th>Professeur</th>		
						</tr>
					</thead>
					<tbody>
						{% for ticket in tickets %}
						<tr>
							<td>
								{% if ticket.calEvent.matiere.nom == matiere_mathematiques %}
									<span class="label label-info">{{ matiere_mathematiques }}</span>
								{% elseif ticket.calEvent.matiere.nom == matiere_physique %}
									<span class="label label-success">{{ matiere_physique }}</span>
								{% elseif ticket.calEvent.matiere.nom == matiere_biologie %}
									<span class="label label-warning">{{ matiere_biologie }}</span>
								{% elseif ticket.calEvent.matiere.nom == matiere_anglais %}
									<span class="label label-important">{{ matiere_anglais }}</span>
								{% elseif ticket.calEvent.matiere.nom == matiere_francais %}
									<span class="label label-default">{{ matiere_francais }}</span>
								{% elseif ticket.calEvent.matiere.nom == matiere_histoire %}
									<span class="label">{{ matiere_histoire }}</span>
								{% endif %}
							</td>
							<td>{{ ticket.dateCours|date('d/m/Y') }}</td>
							<td>
								{% if ticket.calEvent is not null %}
									{{ ticket.calEvent.heureDebut }}
								{% else %}
									Non détaillée
								{% endif %}
							</td>
							<td>
								{% if ticket.calEvent is not null %}
									{{ ticket.calEvent.heureFin }}
								{% else %}
									Non détaillée
								{% endif %}
							</td>
							<td>
								{% if ticket.quantite == 10 %}
									1h
								{% elseif ticket.quantite == 15 %}
									1h30
								{% elseif ticket.quantite == 20 %}
									2h
								{% elseif ticket.quantite == 25 %}
									2h30
								{% elseif ticket.quantite == 30 %}
									3h
								{% elseif ticket.quantite == 40 %}
									4h
								{% elseif ticket.quantite == 50 %}
									5h
								{% elseif ticket.quantite == 195 %}
									19h30
								{% endif %}
							</td>
							<td>{{ ticket.eleve.username }}</td>
							<td>{{ ticket.professeur.username }}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div> #}
		
		{% else %}
		<div class="col-lg-12">
			<em>Aucune heure de cours enregistrée pour l'instant.</em>
		</div>
		<br>
		{% endif %}
		-->
		<br><br>
{% endblock %}